%%

%%

function Data = ImportLeftData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [FRAME,RIGHTSHOULDERFLEXTIME,RIGHTSHOULDERROTATIONTIME,RIGHTSHOULDERABDUCTIONTIME,RIGHTELBOWFLEXTIME,RIGHTWRISTFLEXTIME,LEFTSHOULDERFLEXTIME,LEFTSHOULDERROTATIONTIME,LEFTSHOULDERABDUCTIONTIME,LEFTELBOWFLEXTIME,LEFTWRISTFLEXTIME,R_HAND_X,R_HAND_Y,R_HAND_Z,L_HAND_X,L_HAND_Y,L_HAND_Z,PC,POSTERIORDELTOID,BICEPS,TRICEPS_LATERAL,TRICEPS_LONG,TRIGGER]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [FRAME,RIGHTSHOULDERFLEXTIME,RIGHTSHOULDERROTATIONTIME,RIGHTSHOULDERABDUCTIONTIME,RIGHTELBOWFLEXTIME,RIGHTWRISTFLEXTIME,LEFTSHOULDERFLEXTIME,LEFTSHOULDERROTATIONTIME,LEFTSHOULDERABDUCTIONTIME,LEFTELBOWFLEXTIME,LEFTWRISTFLEXTIME,R_HAND_X,R_HAND_Y,R_HAND_Z,L_HAND_X,L_HAND_Y,L_HAND_Z,PC,POSTERIORDELTOID,BICEPS,TRICEPS_LATERAL,TRICEPS_LONG,TRIGGER]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Frame,RightShoulderFlexTime,RightShoulderRotationTime,RightShoulderAbductionTime,RightElbowFlexTime,RightWristFlexTime,LeftShoulderFlexTime,LeftShoulderRotationTime,LeftShoulderAbductionTime,LeftElbowFlexTime,LeftWristFlexTime,R_hand_x,R_hand_y,R_hand_z,L_hand_x,L_hand_y,L_hand_z,PC,Posteriordeltoid,Biceps,Triceps_lateral,Triceps_long,Trigger]
%   = importfile('FES_S01_L_FR_T01.exp',9, 24108);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/07/26 21:01:18

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 9;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Data.Frame = dataArray{:, 1};
Data.LeftShoulderFlex = dataArray{:, 2};
Data.LeftShoulderRotation = dataArray{:, 3};
Data.LeftShoulderAbduction = dataArray{:, 4};
Data.LeftElbowFlex = dataArray{:, 5};
Data.LeftWristFlex = dataArray{:, 6};
Data.L_acro_x = dataArray{:, 7};
Data.L_acro_y = dataArray{:, 8};
Data.L_acro_z = dataArray{:, 9};
Data.L_olec_x = dataArray{:, 10};
Data.L_olec_y = dataArray{:, 11};
Data.L_olec_z = dataArray{:, 12};
Data.L_hand_x = dataArray{:, 13};
Data.L_hand_y = dataArray{:, 14};
Data.L_hand_z = dataArray{:, 15};
Data.Trigger = dataArray{:, 16};

